name: Node.js CI Pipeline

on:
  pull_request:
    branches:
      - devel
      - stage
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 15.5.1

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install && npm install --save-dev prettier

      # Step 4: Run ESLint
      - name: Run linter
        run: npm run lint

      # Step 5: Run Prettier (Auto-fix)
      - name: Run Prettier auto-fix
        run: npx prettier --write .

      # Step 6: Run tests with Jest
      - name: Run tests
        run: CI=true npm run test

      # Step 7: Build the project
      - name: Build the project
        run: npm run build

      # Step 8: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 9: Deploy to S3 based on the branch
      - name: Deploy to S3 based on the target branch
        run: |
          if [ "${{ github.base_ref }}" == "devel" ]; then
            aws s3 sync ./public s3://fsl-devops-challenger-devel/ --delete
          elif [ "${{ github.base_ref }}" == "stage" ]; then
            aws s3 sync ./public s3://fsl-devops-challenger-stage/ --delete
          elif [ "${{ github.base_ref }}" == "prod" ]; then
            aws s3 sync ./public s3://fsl-devops-challenger-prod/ --delete
          else
            echo "Branch not configured for S3 deployment"
            exit 1
